baseURL: "https://buihien.org"
languageCode: en-us
title: Tech's Blog
theme: PaperMod

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: blog
          name: Blog
          url: /blog
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags
          weight: 30
        - identifier: search
          name: Search
          url: /search
          weight: 40

        # - identifier: notes
        #   name: Notes
        #   url: https://notes.arkalim.org
        #   weight: 70

params:
    # theme
    showToc: true
    TocOpen: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideMeta: false

    # for enchanced SEO
    env: production

    # Home Page
    profileMode:
        enabled: true
        title: "Bùi Hiên"
        subtitle: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
        imageUrl: "home/avatar.png"
        imageWidth: 220
        imageHeight: 220
        # buttons:
        #   - name: Resume
        #     url: ""

    # List View
    hideDescriptionInList: false

    # cover image for posts
    cover:
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    socialIcons:
        - name: "email"
          url: "mailto:hien@techmaster@gmail.com"
        - name: "github"
          url: "https://github.com/buihien0109"
        - name: "instagram"
          url: "https://instagram.com/hienbui219"
        - name: "facebook"
          url: "https://facebook.com/buihiennnn"
        - name: "cv"
          url: "https://media.techmaster.vn/api/static/file/rsRViKG4"

    # text search
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
    home:
        - HTML
        - RSS
        - JSON

# allow HTML in MD
markup:
    goldmark:
        renderer:
            unsafe: true
